version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker pull $REPOSITORY_URI:latest || true
  build:
    commands:
      - echo Started on `date`
      - echo Build Docker image
      - docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG ./
      - echo Tag Docker image
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build completed on `date`
      - echo Push the Docker image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Create Deploy env file"
      - rm -f .env
      - echo '#!/bin/bash' >> .env
      - echo "export IMAGE_NAME=$REPOSITORY_URI" >> .env
      - echo "export IMAGE_TAG=$IMAGE_TAG" >> .env
      - echo "export REGION=$AWS_DEFAULT_REGION" >> .env
      - chmod +x .env

artifacts:
  files:
    - codedeploy/**/*
    - appspec.yml
    - docker-compose.yml
    - .env
